### ISSUE TITLE
cannot submit this package to anaconda package

### ISSUE THREAD

**Issue by wasdee** [wasdee/thaifin#3]
After publish to PyPI, I would like to set up this package in anaconda as well.
In branch `conda-build`, I have try a lots of ways all lead to unsuccess.

1. I follow a [conda-build tutorial](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html) and create a template for the thaifin pypi pkg.
2. run `conda-build thaifin`
3. The unmodified `meta.yaml` fail with the `ModuleNotFoundError: No module named 'poetry'` plus, `raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/n2/miniconda3/conda-bld/thaifin_1612083804251/work/conda_build.sh']' returned non-zero exit status 2.`

<details>
<summary>below are full error log</summary>

```
(base) n2@DESKTOP-K3PRIP7:/mnt/c/Users/n2/devs/circleoncircles/thaifin$ conda-build conda
Multiple meta files found. The meta.yaml file in the base directory (/mnt/c/Users/n2/devs/circleoncircles/thaifin/conda) will be used.
WARNING:conda_build.utils:Multiple meta files found. The meta.yaml file in the base directory (/mnt/c/Users/n2/devs/circleoncircles/thaifin/conda) will be used.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for thaifin
INFO:conda_build.metadata:Attempting to finalize metadata for thaifin
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['thaifin-0.2.2-py38_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
ld_placehold_placehold_placehold_placeh


The following NEW packages will be INSTALLED:

    _libgcc_mutex:      0.1-conda_forge            conda-forge
    _openmp_mutex:      4.5-1_gnu                  conda-forge
    arrow:              0.16.0-py38h32f6830_0      conda-forge
    beautifulsoup4:     4.9.3-pyhb0f4dca_0         conda-forge
    brotlipy:           0.7.0-py38h497a2fe_1001    conda-forge
    ca-certificates:    2020.12.5-ha878542_0       conda-forge
    cachetools:         4.2.1-pyhd8ed1ab_0         conda-forge
    certifi:            2020.12.5-py38h578d9bd_1   conda-forge
    cffi:               1.14.4-py38ha65f79e_1      conda-forge
    chardet:            4.0.0-py38h578d9bd_1       conda-forge
    cryptography:       3.3.1-py38h2b97feb_1       conda-forge
    furl:               2.1.0-py_0                 conda-forge
    fuzzywuzzy:         0.18.0-pyhd8ed1ab_0        conda-forge
    icu:                68.1-h58526e2_0            conda-forge
    idna:               2.10-pyh9f0ad1d_0          conda-forge
    ld_impl_linux-64:   2.35.1-hea4e1c9_1          conda-forge
    libblas:            3.9.0-7_openblas           conda-forge
    libcblas:           3.9.0-7_openblas           conda-forge
    libffi:             3.3-h58526e2_2             conda-forge
    libgcc-ng:          9.3.0-h2828fa1_18          conda-forge
    libgfortran-ng:     9.3.0-hff62375_18          conda-forge
    libgfortran5:       9.3.0-hff62375_18          conda-forge
    libgomp:            9.3.0-h2828fa1_18          conda-forge
    libiconv:           1.16-h516909a_0            conda-forge
    liblapack:          3.9.0-7_openblas           conda-forge
    libopenblas:        0.3.12-pthreads_h4812303_1 conda-forge
    libstdcxx-ng:       9.3.0-h6de172a_18          conda-forge
    libxml2:            2.9.10-h72842e0_3          conda-forge
    libxslt:            1.1.33-h15afd5d_2          conda-forge
    lxml:               4.6.2-py38hf1fe3a4_1       conda-forge
    ncurses:            6.2-h58526e2_4             conda-forge
    numpy:              1.19.5-py38h18fd61f_1      conda-forge
    openssl:            1.1.1i-h7f98852_0          conda-forge
    orderedmultidict:   1.0.1-py_0                 conda-forge
    pandas:             1.2.1-py38h51da96c_0       conda-forge
    pip:                21.0.1-pyhd8ed1ab_0        conda-forge
    pycparser:          2.20-pyh9f0ad1d_2          conda-forge
    pydantic:           1.7.3-py38h497a2fe_0       conda-forge
    pyopenssl:          20.0.1-pyhd8ed1ab_0        conda-forge
    pysocks:            1.7.1-py38h578d9bd_3       conda-forge
    python:             3.8.6-hffdb5ce_5_cpython   conda-forge
    python-dateutil:    2.8.1-py_0                 conda-forge
    python-levenshtein: 0.12.1-py38h497a2fe_0      conda-forge
    python_abi:         3.8-1_cp38                 conda-forge
    pytz:               2020.5-pyhd8ed1ab_0        conda-forge
    readline:           8.0-he28a2e2_2             conda-forge
    requests:           2.25.1-pyhd3deb0d_0        conda-forge
    setuptools:         49.6.0-py38h578d9bd_3      conda-forge
    six:                1.15.0-pyh9f0ad1d_0        conda-forge
    soupsieve:          2.0.1-py_1                 conda-forge
    sqlite:             3.34.0-h74cdb3f_0          conda-forge
    tenacity:           6.3.1-pyhd8ed1ab_0         conda-forge
    tk:                 8.6.10-h21135ba_1          conda-forge
    urllib3:            1.26.3-pyhd8ed1ab_0        conda-forge
    wheel:              0.36.2-pyhd3deb0d_0        conda-forge
    xz:                 5.2.5-h516909a_1           conda-forge
    zlib:               1.2.11-h516909a_1010       conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: /home/n2/miniconda3/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /home/n2/miniconda3/conda-bld/src_cache
INFO conda_build.source:download_to_cache(44): Source cache directory is: /home/n2/miniconda3/conda-bld/src_cache
Found source in cache: thaifin-0.2.2_2b384dfe3f.tar.gz
INFO:conda_build.source:Found source in cache: thaifin-0.2.2_2b384dfe3f.tar.gz
INFO conda_build.source:download_to_cache(66): Found source in cache: thaifin-0.2.2_2b384dfe3f.tar.gz
Extracting download
source tree in: /home/n2/miniconda3/conda-bld/thaifin_1612083804251/work
export PREFIX=/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
ld_placehold_placehold_placeh
export BUILD_PREFIX=/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_build_env
export SRC_DIR=/home/n2/miniconda3/conda-bld/thaifin_1612083804251/work
Using pip 21.0.1 from $PREFIX/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-p5th0489
Created temporary directory: /tmp/pip-req-tracker-h4pkgzjg
Initialized build tracking at /tmp/pip-req-tracker-h4pkgzjg
Created build tracker: /tmp/pip-req-tracker-h4pkgzjg
Entered build tracker: /tmp/pip-req-tracker-h4pkgzjg
Created temporary directory: /tmp/pip-install-836s_70f
Processing $SRC_DIR
  Created temporary directory: /tmp/pip-req-build-7_evlugr
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-h4pkgzjg'
    Created temporary directory: /tmp/pip-modern-metadata-yfnb95m1
    Preparing wheel metadata: started
    Running command /home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_placeh/bin/python /home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
ehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp150j1_dx
    Preparing wheel metadata: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 100, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 301, in make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 300, in __init__
    super().__init__(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 311, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 500, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 66, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 549, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 534, in _generate_metadata
    return generate_metadata(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_internal/operations/build/metadata.py", line 34, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 193, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 284, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/home/n2/miniconda3/conda-bld/thaifin_1612083804251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
cehold_placehold_placeh/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'

Removed file://$SRC_DIR from build tracker '/tmp/pip-req-tracker-h4pkgzjg'
Removed build tracker: '/tmp/pip-req-tracker-h4pkgzjg'
Traceback (most recent call last):
  File "/home/n2/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/n2/miniconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/home/n2/miniconda3/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/home/n2/miniconda3/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/home/n2/miniconda3/lib/python3.8/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/n2/miniconda3/lib/python3.8/site-packages/conda_build/build.py", line 2191, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/home/n2/miniconda3/lib/python3.8/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/n2/miniconda3/lib/python3.8/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/n2/miniconda3/conda-bld/thaifin_1612083804251/work/conda_build.sh']' returned non-zero exit status 2.
```

</details>

what i have try along with some cross combination of them.
1. fix pip version [ref](https://github.com/conda-forge/dolang-feedstock/issues/1)
2. add poetry to host dependency
3. use poetry to install instead of pip `"{{ PYTHON }} -m poetry config virtualenvs.create false && {{ PYTHON }} -m poetry install --no-root --no-dev"`
4. add `--no-deps` to `pip install `
5. use local dir as source instead of pypi source

num 3 will end up with another log error about fail import test.

please help me anyone 🙏 All works are in branch `conda-build`, you can pull and reproduce.

**Comment by benoit-cty** [comment]
Hello, for those commit here from a search engine, I solved this error in my project by adding poetry to host dependencies:
```
requirements:
  host:
    - python
    - pip
    - poetry
```

**Comment by wasdee** [comment]
> requirements:

thank you

I found [https://github.com/conda/grayskull]. and it is working the same way like you sugestion.
